AWSTemplateFormatVersion: 2010-09-09

Transform: AWS::Serverless-2016-10-31

Description: Infrastructure provisioning for a serverless, performant and cost-efficient proof-of-concept chat application built with free tier AWS resources.

Globals:
  Function:
    Timeout: 180
    Handler: bootstrap.is.the.handler
    Runtime: provided.al2
    Environment:
      Variables:
        PUBLIC_BUCKET: !Ref PublicMediaBucket
        TABLE_NAME: !Ref MainTable
    Architectures:
      - arm64

Resources:
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: ChatApp-UserPool
      AutoVerifiedAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
      Schema:
        - AttributeDataType: String
          Name: email
          Required: true
        - AttributeDataType: String
          Name: name
          Required: true

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: ChatApp-Client
      ExplicitAuthFlows:
        - ADMIN_NO_SRP_AUTH
        - USER_PASSWORD_AUTH
      GenerateSecret: true
      UserPoolId: !Ref UserPool

  MainTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: MainTable
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: partitionKey
          AttributeType: S
        - AttributeName: sortKey
          AttributeType: S
        - AttributeName: gsi1PK
          AttributeType: S
        - AttributeName: gsi1SK
          AttributeType: S
        - AttributeName: gsi2PK
          AttributeType: S
        - AttributeName: gsi2SK
          AttributeType: S
      KeySchema:
        - AttributeName: partitionKey
          KeyType: HASH
        - AttributeName: sortKey
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: GSI1
          KeySchema:
            - AttributeName: gsi1PK
              KeyType: HASH
            - AttributeName: gsi1SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: GSI2
          KeySchema:
            - AttributeName: gsi2PK
              KeyType: HASH
            - AttributeName: gsi2SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  PublicMediaBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName: chat-app-public-media
      AccessControl: PublicRead
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - "*"
            AllowedMethods:
              - GET
            AllowedOrigins:
              - "*"

  PublicMediaBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref PublicMediaBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - "s3:GetObject"
            Effect: Allow
            Resource: !Join
              - ""
              - - !GetAtt PublicMediaBucket.Arn
                - /*
            Principal: "*"

  GetUserInfoLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/lambda/get-user-info-lambda
      FunctionName: APIGetUserInfoLambda
      Environment:
        Variables:
          USERPOOL_ID: !Ref UserPool
      Events:
        RestAPI:
          Type: Api
          Properties:
            Path: /user
            Method: get
      Policies:
        - Statement:
            - Sid: CognitoFullAccessPolicy
              Effect: Allow
              Action: cognito-idp:*
              Resource: !GetAtt UserPool.Arn

  PostConfirmationLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/lambda/cognito-post-confirmation-lambda
      FunctionName: CognitoPostConfirmationLambda
      Events:
        CognitoEvent:
          Type: Cognito
          Properties:
            UserPool: !Ref UserPool
            Trigger: PostConfirmation
      Policies:
        - S3WritePolicy:
            BucketName: !Ref PublicMediaBucket

Outputs:
  RestAPI:
    Description: API Gateway URL
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/"
  PublicBucketURL:
    Description: URL for fetching resources from the public bucket
    Value: !GetAtt PublicMediaBucket.DomainName
